-- MENAMPILKAN SEMUA KATEGORI
SELECT * FROM kategori;

-- MENAMPILKAN SEMUA BARANG
SELECT * FROM barang;

-- MENAMPILKAN DATA SUPPLIER
SELECT * FROM supplier;

-- MENAMPILKAN DATA PEGAWAI
SELECT * FROM pegawai;

-- MENAMPILKAN DATA PELANGGAN
SELECT * FROM pelanggan;

-- MENAMPILKAN DATA PEMBELIAN
SELECT * FROM pembelian;

-- MENAMPILKAN DETAIL PEMBELIAN
SELECT * FROM detail_pembelian;

-- MENAMPILKAN DATA PENJUALAN
SELECT * FROM penjualan;

-- MENAMPILKAN DETAIL PENJUALAN
SELECT * FROM detail_penjualan;
